#
# Makefile for TACACS+ unit tests
#

ALL = dummy
all : $(ALL)
.PHONY : all clean

# .SUFFIXES:
# .SUFFIXES: .c .o .h

#settings
# CC = gcc
# COMP = $(CC) -c
# LINK = $(CC)

#dependencies
# dummy:	dummy.o

#rules
# %:	%.o
	# $(LINK) -o $@ $^

# %.o:	%.c
	# $(COMP) -o $@ $<

clean:
	rm -fr $(ALL) *.o

